// <auto-generated />
using ApiCadastrarVeiculo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCadastrarVeiculo.Migrations
{
    [DbContext(typeof(VeiculoContext))]
    [Migration("20250529013915_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ApiCadastrarVeiculo.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chassis = "CHS001",
                            Cor = "Prata",
                            Marca = "Chevrolet",
                            Modelo = "Onix",
                            Placa = "ABC1234",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 2,
                            Chassis = "CHS002",
                            Cor = "Preto",
                            Marca = "Honda",
                            Modelo = "Civic",
                            Placa = "DEF5678",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 3,
                            Chassis = "CHS003",
                            Cor = "Branco",
                            Marca = "Volkswagen",
                            Modelo = "Gol",
                            Placa = "GHI9012",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 4,
                            Chassis = "CHS004",
                            Cor = "Azul",
                            Marca = "Ford",
                            Modelo = "Fiesta",
                            Placa = "JKL3456",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 5,
                            Chassis = "CHS005",
                            Cor = "Vermelho",
                            Marca = "Hyundai",
                            Modelo = "HB20",
                            Placa = "MNO7890",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 6,
                            Chassis = "CHS006",
                            Cor = "Cinza",
                            Marca = "Ford",
                            Modelo = "Ka",
                            Placa = "PQR1234",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 7,
                            Chassis = "CHS007",
                            Cor = "Preto",
                            Marca = "Fiat",
                            Modelo = "Palio",
                            Placa = "STU5678",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 8,
                            Chassis = "CHS008",
                            Cor = "Branco",
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Placa = "VWX9012",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 9,
                            Chassis = "CHS009",
                            Cor = "Azul",
                            Marca = "Chevrolet",
                            Modelo = "Cruze",
                            Placa = "YZA3456",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 10,
                            Chassis = "CHS010",
                            Cor = "Verde",
                            Marca = "Fiat",
                            Modelo = "Uno",
                            Placa = "BCD7890",
                            Status = "Recuperado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
